version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule: { interval: weekly }
  - package-ecosystem: composer
    directory: /
    schedule: { interval: weekly }
    target-branch: dev
    open-pull-requests-limit: 5
