<?php

declare(strict_types=1);

namespace ElevateDxp\Workflow\Config;

use ElevateDxp\Workflow\Model\WorkflowDefinition;
use ElevateDxp\Workflow\Store\WorkflowYamlStore;
use Symfony\Component\Yaml\Yaml;

/**
 * "Apply": writes the opendxp.workflows fragment of a definition to
 * <project>/<apply_dir>/elevate_dxp_workflow_<name>.yaml (config/local is imported by the app config).
 *
 * Workflows are compiled into the container, so the change is only active after
 * `bin/console cache:clear` — apply is intentionally a write + pending-rebuild operation.
 */
class WorkflowConfigWriter
{
    public const STATUS_APPLIED = 'applied';
    public const STATUS_OUTDATED = 'outdated';
    public const STATUS_NOT_APPLIED = 'not_applied';

    private const HEADER = "# Generated by the Elevate DXP workflow designer — do not edit by hand.\n"
        ."# Activate changes with: bin/console cache:clear\n";

    public function __construct(
        private readonly string $projectDir,
        private readonly string $applyDir = 'config/local',
    ) {
    }

    public function path(string $name): string
    {
        return rtrim($this->projectDir, '/').'/'.trim($this->applyDir, '/').'/elevate_dxp_workflow_'.WorkflowYamlStore::safeName($name).'.yaml';
    }

    public function render(WorkflowDefinition $def): string
    {
        return self::HEADER.Yaml::dump($def->toOpenDxpConfig(), 8, 2);
    }

    public function write(WorkflowDefinition $def): string
    {
        $file = $this->path($def->name);
        $dir = \dirname($file);
        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new \RuntimeException('Cannot create config dir: '.$dir);
        }
        if (file_put_contents($file, $this->render($def), \LOCK_EX) === false) {
            throw new \RuntimeException('Cannot write '.$file);
        }

        return $file;
    }

    public function remove(string $name): bool
    {
        $file = $this->path($name);

        return is_file($file) && unlink($file);
    }

    public function status(WorkflowDefinition $def): string
    {
        $file = $this->path($def->name);
        if (!is_file($file)) {
            return self::STATUS_NOT_APPLIED;
        }

        return file_get_contents($file) === $this->render($def) ? self::STATUS_APPLIED : self::STATUS_OUTDATED;
    }
}
