<?php

declare(strict_types=1);

namespace ElevateDxp\Feed\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $tb = new TreeBuilder('feed');
        $tb->getRootNode()
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')->defaultTrue()->end()
                ->integerNode('chunk_size')->defaultValue(100)->min(1)->end()
                ->arrayNode('feeds')
                    ->useAttributeAsKey('name')->normalizeKeys(false)
                    ->validate()
                        ->ifTrue(static fn (array $feeds): bool => array_filter(array_keys($feeds), static fn ($k): bool => !preg_match('/^[A-Za-z0-9_-]+$/', (string) $k)) !== [])
                        ->thenInvalid('Feed names may only contain letters, digits, "_" and "-".')
                    ->end()
                    ->arrayPrototype()
                        ->children()
                            ->arrayNode('source')
                                ->isRequired()
                                ->children()
                                    ->enumNode('type')->values(['data_object', 'asset'])->isRequired()->end()
                                    ->scalarNode('class')->defaultNull()->end()
                                ->end()
                            ->end()
                            ->enumNode('template')->values(['generic_csv', 'google_merchant'])->isRequired()->end()
                            ->scalarNode('currency')->defaultValue('EUR')->end()
                            ->scalarNode('link_pattern')->defaultNull()
                                ->info('Optional link builder, e.g. https://shop.example.com/p/{id}')->end()
                            ->arrayNode('mappings')->useAttributeAsKey('name')->normalizeKeys(false)->scalarPrototype()->end()->end()
                            ->arrayNode('static')->useAttributeAsKey('name')->normalizeKeys(false)->scalarPrototype()->end()->end()
                            ->arrayNode('channel')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('title')->defaultValue('Product feed')->end()
                                    ->scalarNode('link')->defaultValue('https://example.com')->end()
                                    ->scalarNode('description')->defaultValue('Generated by Elevate DXP')->end()
                                ->end()
                            ->end()
                            ->arrayNode('target')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->enumNode('type')->values(['local', 'asset', 'http'])->defaultValue('local')->end()
                                    ->scalarNode('path')->defaultNull()->end()
                                ->end()
                            ->end()
                            ->scalarNode('token')->defaultNull()
                                ->info('Secret for the public URL /elevate-dxp/feed/{name}.{format}?token=... (min 16 chars, use an env var). No token = no public URL.')->end()
                            ->integerNode('cache_ttl')->defaultValue(300)->min(0)
                                ->info('Seconds the public URL serves a cached rendering (0 = render on every request).')->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $tb;
    }
}
